project:
  type: website
  output-dir: docs

brand:
  light: light-brand.yml
  dark: dark-brand.yml

website:
  title: "Indicare Salute Lab"
  navbar:
    left:
      - text: Home
        href: index.qmd
      - about.qmd

format:
  html:
    css: styles.css
    lang: it
    respect-user-color-scheme: true

execute:
  echo: false



