project:
  type: website
  output-dir: docs

brand:
  light: light-brand.yml
  dark: dark-brand.yml

website:
  title: "Indicare Salute Lab"
  navbar:
    left:
      - text: Home
        href: index.qmd
      - about.qmd
    tools:
      - icon: box-arrow-in-left
        text: Accedi alla piattaforma
        href: https://upipa.shinyapps.io/IndicareSalute2/
  page-footer:
    left:
      - icon: telephone
        text: "+39 0461 39.00.25<br>indicaresalutelab@upipa.tn.it"
    center:
      - icon: geo-alt
        text: "Via Sighele, 7<br>38122 TRENTO"
    right:
      - icon: clock
        text: "09:00 - 13:00<br>Lunerdì - Venerdì"
  search: false
        

format:
  html:
    css: styles.css
    lang: it
    respect-user-color-scheme: true

execute:
  echo: false
  warning: false
  message: false



