project:
  type: website
  resources: 
    - google4fe49397b5a959bb.html
  output-dir: docs

brand:
  light: light-brand.yml
  dark: dark-brand.yml

website:
  title: "Indicare Salute Lab"
  favicon: logos/islab-logo.png
  navbar:
    left:
      - text: Home
        href: index.qmd
      - text: Chi siamo
        href: about.qmd
      - text: Progetto
        href: progetto.qmd
      - text: Contatti
        href: contatti.qmd
    right:
      - text: Accedi alla piattaforma
        icon: box-arrow-in-left
        href: https://upipa.shinyapps.io/IndicareSalute2/
        
  search: false
        
format:
  html:
    css: styles.css
    lang: it
    respect-user-color-scheme: true

execute:
  echo: false
  warning: false
  message: false



