---
title: "A.p.s.p. Residenza Valle dei Laghi"
format: html
---

La “Residenza valle dei laghi" di Cavedine, è un’ Azienda Pubblica di Servizi alla Persona che intende proporsi come luogo di ospitalità e di supporto morale ad anziani in condizioni di disagio. Il contesto ambientale e relazionale, fortemente connotato da caratteristiche tipiche dell’ambito familiare, consente un fattivo compimento di quella Centralità della Persona che rappresenta il filo d’Arianna verso un nuovo umanesimo nell’assistenza all’anziano.

La Residenza è situata a Cavedine, a quota 504 m s.l.m. e dista 24 km da Trento e 22 Km da Riva del Garda. La struttura è dotata di ampi spazi verdi con giardino attrezzato, fruibili dagli ospiti. Le camere, singole o doppie, sono dotate di comodo bagno, predisposto per persone disabili, di impianto TV e di climatizzazione. E’ presente un’accogliente sala da pranzo oltre ad ampi spazi per la socializzazione, area bar, locali per la riabilitazione e un’intima chiesetta interna.

La “Residenza valle dei laghi” di Cavedine, fa propria la mission dell’ International Society for Augmentative and Alternative Communication per lo sviluppo delle tecnologie di comunicazione aumentativa e alternativa.